const GET_IMAGE_DATA_FROM_API = 'GET_IMAGE_DATA_FROM_API'
const IMAGE_DATA_LOADED = 'IMAGE_DATA_LOADED'
const MAX_IMAGES_PER_PAGE = 20
const ADD_FAVOURITE = 'ADD_FAVOURITE'
const REMOVE_FAVOURITE = 'REMOVE_FAVOURITE'
const MODAL_BTN_TEXT = 'OK'
const OPEN_MODAL = 'OPEN_MODAL'
const CLOSE_MODAL = 'CLOSE_MODAL'
const TOGGLE_MODAL = 'TOGGLE_MODAL'

export {
  IMAGE_DATA_LOADED,
  GET_IMAGE_DATA_FROM_API,
  MAX_IMAGES_PER_PAGE,
  ADD_FAVOURITE,
  REMOVE_FAVOURITE,
  MODAL_BTN_TEXT,
  OPEN_MODAL,
  CLOSE_MODAL,
  TOGGLE_MODAL
}